### ISSUE TITLE
Improve validation and error message when parsing invalid srv

### ISSUE THREAD

**Issue by tfoote** [ros2/rosidl#12]
When I had a typo in a service referencing an non-existant message as a subtype, it made it all the way through the generation and failed on missing include directories when actually trying to compile the c++ type support. 

We should find a way to validate this earlier and catch that it's referencing a message which does not exist and provide an error message to that effect before running generation for n languages and trying to compile some of them. 

For the moment this is a low priority but should be fixed before release. 

For reference this is the error shown for an invalid reference to Parameters which should be Parameter
```
In file included from /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_cpp/rcl_interfaces/GetParametersResponse.h:4:0,
                 from /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_cpp/rcl_interfaces/GetParameters_Service.h:5,
                 from /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_introspection_cpp/rcl_interfaces/GetParameters_ServiceTypeSupport_Introspection.cpp:10:
/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_cpp/rcl_interfaces/GetParametersResponse_Struct.h:12:39: fatal error: rcl_interfaces/Parameters.h: No such file or directory
 #include <rcl_interfaces/Parameters.h>
                                       ^
compilation terminated.
[  7%] Generating C++ type support for PrismTech OpenSplice
make[2]: *** [CMakeFiles/rcl_interfaces__typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/rcl_interfaces/GetParameters_ServiceTypeSupport_Introspection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/rcl_interfaces__typesupport_introspection_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParameterDescription_.idl line 35  preprocessor directive not supported. It will be ignored
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer Parameter_.idl line 30  preprocessor directive not supported. It will be ignored
INFO com.rti.ndds.nddsgen.Main Done
Generating: /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/ParameterDescription_.h/cpp
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParameterDescription_.idl line 35  preprocessor directive not supported. It will be ignored
INFO com.rti.ndds.nddsgen.Main Done
Generating: /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/ParameterEvent_.h/cpp
"/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl/rcl_interfaces/dds_opensplice/GetParametersResponse_.idl", line 7: can't find include file rcl_interfaces/dds_opensplice/Parameters_.idl
***DDS parse error Parameters_ undefined at line: 20 (searching from scope 'dds_')
Traceback (most recent call last):
  File "/home/tfoote/work/ros2/parameters/install/lib/rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp", line 68, in <module>
    sys.exit(main())
  File "/home/tfoote/work/ros2/parameters/install/lib/rosidl_typesupport_opensplice_cpp/rosidl_typesupport_opensplice_cpp", line 54, in main
    args.idl_pp,
  File "/home/tfoote/work/ros2/parameters/install/lib/python3.4/site-packages/rosidl_typesupport_opensplice_cpp/__init__.py", line 50, in generate_dds_opensplice_cpp
    subprocess.check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/idlpp', '-I', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl', '-S', '-l', 'cpp', '-o', 'dds-types', '-d', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_opensplice_cpp/rcl_interfaces/dds_opensplice', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl/rcl_interfaces/dds_opensplice/SampleGetParametersResponse_.idl']' returned non-zero exit status 255
make[2]: *** [rosidl_typesupport_opensplice_cpp/rcl_interfaces/dds_opensplice/Parameter_.h] Error 1
make[1]: *** [CMakeFiles/rcl_interfaces__dds_opensplice_cpp.dir/all] Error 2
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParameterDescription_.idl line 35  preprocessor directive not supported. It will be ignored
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer Parameter_.idl line 30  preprocessor directive not supported. It will be ignored
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParameterEvent_.idl line 28  preprocessor directive not supported. It will be ignored
INFO com.rti.ndds.nddsgen.Main Done
Generating: /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/GetParametersRequest_.h/cpp
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer ParameterDescription_.idl line 35  preprocessor directive not supported. It will be ignored
WARN com.rti.ndds.nddsgen.antlr.auto.IdlLexer GetParametersRequest_.idl line 25  preprocessor directive not supported. It will be ignored
INFO com.rti.ndds.nddsgen.Main Done
Generating: /home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/GetParametersResponse_.h/cpp
INFO com.rti.ndds.nddsgen.Main Running rtiddsgen version 2.2.0.0, please wait ...
/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl/rcl_interfaces/dds_connext/GetParametersResponse_.idl:6:54: fatal error: rcl_interfaces/dds_connext/Parameters_.idl: No such file or directory
 #include "rcl_interfaces/dds_connext/Parameters_.idl"
                                                      ^
compilation terminated.
ERROR com.rti.ndds.nddsgen.Main Fail:  Error executing cpp preprocessor
INFO com.rti.ndds.nddsgen.Main Done (failures)
Traceback (most recent call last):
  File "/home/tfoote/work/ros2/parameters/install/lib/rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp", line 75, in <module>
    sys.exit(main())
  File "/home/tfoote/work/ros2/parameters/install/lib/rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp", line 61, in main
    service_specs,
  File "/home/tfoote/work/ros2/parameters/install/lib/python3.4/site-packages/rosidl_typesupport_connext_cpp/__init__.py", line 74, in generate_dds_connext_cpp
    subprocess.check_call(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/rtiddsgen2', '-I', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl', '-d', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext', '-language', 'C++', '-namespace', '-replace', '/home/tfoote/work/ros2/parameters/build/rcl_interfaces/rosidl_generator_dds_idl/rcl_interfaces/dds_connext/GetParametersResponse_.idl']' returned non-zero exit status 255
make[2]: *** [rosidl_typesupport_connext_cpp/rcl_interfaces/dds_connext/Parameter_.h] Error 1
make[1]: *** [CMakeFiles/rcl_interfaces__dds_connext_cpp.dir/all] Error 2
make: *** [all] Error 2

<== Command '. /home/tfoote/work/ros2/parameters/build/rcl_interfaces/ament_cmake__build.sh && /usr/bin/make -j8 -l8' failed with exit code '2'
```

**Comment by dirk-thomas** [comment]
The parser itself should not be aware of this but generators which will actually compile the generated code afterwards should be able to verify that all message dependencies are known.

The referenced PRs will address this.
