### ISSUE TITLE
Message generation fails if line ends with #[...]

### ISSUE THREAD

**Issue by hdino** [ros2/rosidl#405]
## Bug report
- Operating System: Ubuntu 18.04
- Installation type: Binaries
- Version or commit hash: 0.7.5-1bionic.20190823.205203

#### Steps to reproduce issue
Create a message definition file containing a line ending with `#[...]`, for instance:
```
float64 longitude #[x]
```

#### Actual behavior
Message generation fails with an exception:
```
Error processing idl file: example.idl
Traceback (most recent call last):
  File "/opt/ros/dashing/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 40, in <module>
    sys.exit(main())
  File "/opt/ros/dashing/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 35, in main
    args.generator_arguments_file,
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_generator_cpp/__init__.py", line 37, in generate_cpp
    generate_files(generator_arguments_file, mapping)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_cmake/__init__.py", line 90, in generate_files
    raise(e)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_cmake/__init__.py", line 70, in generate_files
    idl_file = parse_idl_file(locator)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 64, in parse_idl_file
    content = parse_idl_string(string, png_file=png_file)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 73, in parse_idl_string
    content = extract_content_from_ast(tree)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 144, in extract_content_from_ast
    add_message_members(msg, struct_defs[0])
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 367, in add_message_members
    annotations = get_annotations(member)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 512, in get_annotations
    get_const_expr_value(const_expr)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 561, in get_const_expr_value
    return get_string_literal_value(child, allow_unicode=False)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rosidl_parser/parser.py", line 592, in get_string_literal_value
    assert len(string_literal.children) == 1
```

**Comment by dirk-thomas** [comment]
Thanks for reporting the problem. #409 should address the problem.

As a temporary workaround any extra characters in the comment beside the unit annotation (`[x]`) will make it pass, e.g.:

`float64 longitude # [x]`
