### ISSUE TITLE
Fails to build empty string in message definition

### ISSUE THREAD

**Issue by sageig** [ros2/rosidl#506]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries 
- Version or commit hash:
  - ros-foxy latest
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Included in the message definition
```
string TYPE_UNKNOWN = ""
```

#### Expected behavior
Build cleanly.

#### Actual behavior
```
Traceback (most recent call last):
  File "/opt/ros/foxy/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 40, in <module>
    sys.exit(main())
  File "/opt/ros/foxy/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 34, in main
    return generate_cpp(
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_cpp/__init__.py", line 38, in generate_cpp
    generate_files(
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 94, in generate_files
    raise(e)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 73, in generate_files
    idl_file = parse_idl_file(locator)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 64, in parse_idl_file
    content = parse_idl_string(string, png_file=png_file)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 73, in parse_idl_string
    content = extract_content_from_ast(tree)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 114, in extract_content_from_ast
    get_abstract_type_from_const_expr(const_type, value),
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 334, in get_abstract_type_from_const_expr
    return BoundedString(len(value))
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/definition.py", line 224, in __init__
    assert maximum_size > 0
AssertionError
```

**Comment by dirk-thomas** [comment]
Thanks for the report. Please see #507 for the proposed fix.
