### ISSUE TITLE
Fails to build messages with float type and small default values

### ISSUE THREAD

**Issue by DariusPietsch** [ros2/rosidl#541]
## Bug report

**Required Info:**

- Operating System:
  - Kubuntu 20.04 
- Installation type:
  - binaries 
- Version or commit hash:
  - ros-foxy latest
- DDS implementation:
  - Fast-RTPS 
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue

Create a message field with a default value smaller than 0.0001: 
```
float64 very_small_number 0.00009
```

#### Expected behavior
successful build
#### Actual behavior
```
Traceback (most recent call last):
  File "/opt/ros/foxy/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 40, in <module>
    sys.exit(main())
  File "/opt/ros/foxy/share/rosidl_generator_cpp/cmake/../../../lib/rosidl_generator_cpp/rosidl_generator_cpp", line 34, in main
    return generate_cpp(
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_cpp/__init__.py", line 38, in generate_cpp
    generate_files(
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
    raise(e)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 74, in generate_files
    idl_file = parse_idl_file(locator)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 64, in parse_idl_file
    content = parse_idl_string(string, png_file=png_file)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 73, in parse_idl_string
    content = extract_content_from_ast(tree)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 158, in extract_content_from_ast
    add_message_members(request, struct_defs[0])
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 367, in add_message_members
    annotations = get_annotations(member)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 513, in get_annotations
    get_const_expr_value(const_expr)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_parser/parser.py", line 528, in get_const_expr_value
    assert len(expr) == 1, str(expr)
AssertionError: [Tree(primary_expr, [Tree(literal, [Tree(floating_pt_literal, [Token(DIGIT, '9'), Tree(floating_pt_literal_e, [])])])]), Tree(primary_expr, [Tree(literal, [Tree(integer_literal, [Tree(octal_literal, [Token(__ANON_1, '5')])])])])]
```

**Comment by clalancette** [comment]
Thanks for reporting.  See https://github.com/ros2/rosidl/pull/542 for a fix .
