### ISSUE TITLE
StopIteration raised in rosidl_parser tests on Ubuntu Jammy

### ISSUE THREAD

**Issue by sloretz** [ros2/rosidl#663]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Jammy
- Installation type:
  - Binaries
- Version or commit hash:
  - master
- DDS implementation:
  - N/A
- Client library (if applicable):
  -  N/A

#### Steps to reproduce issue

Go to the test directory of rosidl_parser

```console
$ cd rosidl_parser/test
```
Create and execute this file

```python3
#!/usr/bin/env python3

from rosidl_parser.definition import IdlLocator
import pathlib
from rosidl_parser.parser import parse_idl_file

print(parse_idl_file(IdlLocator(pathlib.Path('.'), pathlib.Path('msg') / 'MyMessage.idl')))
```

#### Expected behavior

Successful parse on Focal

```
<rosidl_parser.definition.IdlFile object at 0x7fea76fab5b0>
```

#### Actual behavior

StopIteration raised on Jammy

```
Traceback (most recent call last):
  File "/home/osrf/ws/ros2/src/ros2/rosidl/rosidl_parser/test/./quicktest.py", line 7, in <module>
    print(parse_idl_file(IdlLocator(pathlib.Path('.'), pathlib.Path('msg') / 'MyMessage.idl')))
  File "/home/osrf/ws/ros2/install/rosidl_parser/lib/python3.9/site-packages/rosidl_parser/parser.py", line 64, in parse_idl_file
    content = parse_idl_string(string, png_file=png_file)
  File "/home/osrf/ws/ros2/install/rosidl_parser/lib/python3.9/site-packages/rosidl_parser/parser.py", line 73, in parse_idl_string
    content = extract_content_from_ast(tree)
  File "/home/osrf/ws/ros2/install/rosidl_parser/lib/python3.9/site-packages/rosidl_parser/parser.py", line 146, in extract_content_from_ast
    add_message_members(msg, struct_defs[0])
  File "/home/osrf/ws/ros2/install/rosidl_parser/lib/python3.9/site-packages/rosidl_parser/parser.py", line 369, in add_message_members
    annotations = get_annotations(member)
  File "/home/osrf/ws/ros2/install/rosidl_parser/lib/python3.9/site-packages/rosidl_parser/parser.py", line 520, in get_annotations
    const_expr = next(annotation_appl.find_data('const_expr'))
StopIteration

```

#### Additional information

I notice the `lark` Python module on Jammy is version 1.1.1, while on Focal its version 0.8.1.

When I output the AST, it looks different on Jammy vs Focal. At the start of the tree on Focal, it looks like this

```
Tree(const_dcl ...
```

But the same on Jammy has all these "Token('RULE'` classes

```
Tree(Token('RULE', 'const_dcl')...
```

URL with differences between versions because the changelog was pretty short: https://github.com/lark-parser/lark/compare/0.8.1...1.1.1

**Comment by sloretz** [comment]
Might have something to do with the changes to `Tree.iter_subtrees` implementation

1.1.1
https://github.com/lark-parser/lark/blob/01e16c55c75be6ba8199f0873adee7f1a3146678/lark/tree.py#L101-L115

0.8.1
https://github.com/lark-parser/lark/blob/5346231e14d31ab5bbc3cbc014a31b405d40ef39/lark/tree.py#L60-L79

**Comment by sloretz** [comment]
Printing out the parse tree passed to get_annotations(),

<details><summary>0.8.1 succeeds with this tree</summary>

```
Tree(member, [
Tree(annotation_appl, [
Tree(scoped_name, [Token(IDENTIFIER, 'key')])]), 
Tree(annotation_appl, [
Tree(scoped_name, [Token(IDENTIFIER, 'range')]), 
Tree(annotation_appl_params, [
Tree(annotation_appl_param, [Token(IDENTIFIER, 'min'), 
Tree(const_expr, [
Tree(or_expr, [
Tree(xor_expr, [
Tree(and_expr, [
Tree(shift_expr, [
Tree(add_expr, [
Tree(mult_expr, [
Tree(unary_expr, [
Tree(unary_operator, [
Tree(unary_operator_minus, [])]), 
Tree(primary_expr, [
Tree(literal, [
Tree(integer_literal, [
Tree(decimal_literal, [Token(__ANON_0, '1'), Token(DIGIT, '0')])])])])])])])])])])])])]), 
Tree(annotation_appl_param, [Token(IDENTIFIER, 'max'), 
Tree(const_expr, [
Tree(or_expr, [
Tree(xor_expr, [
Tree(and_expr, [
Tree(shift_expr, [
Tree(add_expr, [
Tree(mult_expr, [
Tree(unary_expr, [
Tree(primary_expr, [
Tree(literal, [
Tree(integer_literal, [
Tree(decimal_literal, [Token(__ANON_0, '1'), Token(DIGIT, '0')])])])])])])])])])])])])])])]), 
Tree(type_spec, [
Tree(simple_type_spec, [
Tree(base_type_spec, [
Tree(integer_type, [
Tree(signed_int, [
Tree(signed_long_int, [])])])])])]), 
Tree(declarators, [
Tree(declarator, [
Tree(simple_declarator, [Token(IDENTIFIER, 'long_value')])])])])Tree(member, [
Tree(annotation_appl, [
Tree(scoped_name, [Token(IDENTIFIER, 'key')])]), 
Tree(annotation_appl, [
Tree(scoped_name, [Token(IDENTIFIER, 'range')]), 
Tree(annotation_appl_params, [
Tree(annotation_appl_param, [Token(IDENTIFIER, 'min'), 
Tree(const_expr, [
Tree(or_expr, [
Tree(xor_expr, [
Tree(and_expr, [
Tree(shift_expr, [
Tree(add_expr, [
Tree(mult_expr, [
Tree(unary_expr, [
Tree(unary_operator, [
Tree(unary_operator_minus, [])]), 
Tree(primary_expr, [
Tree(literal, [
Tree(integer_literal, [
Tree(decimal_literal, [Token(__ANON_0, '1'), Token(DIGIT, '0')])])])])])])])])])])])])]), 
Tree(annotation_appl_param, [Token(IDENTIFIER, 'max'), 
Tree(const_expr, [
Tree(or_expr, [
Tree(xor_expr, [
Tree(and_expr, [
Tree(shift_expr, [
Tree(add_expr, [
Tree(mult_expr, [
Tree(unary_expr, [
Tree(primary_expr, [
Tree(literal, [
Tree(integer_literal, [
Tree(decimal_literal, [Token(__ANON_0, '1'), Token(DIGIT, '0')])])])])])])])])])])])])])])]), 
Tree(type_spec, [
Tree(simple_type_spec, [
Tree(base_type_spec, [
Tree(integer_type, [
Tree(signed_int, [
Tree(signed_long_int, [])])])])])]), 
Tree(declarators, [
Tree(declarator, [
Tree(simple_declarator, [Token(IDENTIFIER, 'long_value')])])])])
```
</details>


<details><summary>And 1.1.1 fails with this one</summary>

```
Tree(Token('RULE', 'member'), [
Tree(Token('RULE', 'annotation_appl'), [
Tree(Token('RULE', 'scoped_name'), [Token('IDENTIFIER', 'key')]), None]), 
Tree(Token('RULE', 'annotation_appl'), [
Tree(Token('RULE', 'scoped_name'), [Token('IDENTIFIER', 'range')]), 
Tree(Token('RULE', 'annotation_appl_params'), [
Tree(Token('RULE', 'annotation_appl_param'), [Token('IDENTIFIER', 'min'), 
Tree(Token('RULE', 'const_expr'), [
Tree(Token('RULE', 'or_expr'), [
Tree(Token('RULE', 'xor_expr'), [
Tree(Token('RULE', 'and_expr'), [
Tree(Token('RULE', 'shift_expr'), [
Tree(Token('RULE', 'add_expr'), [
Tree(Token('RULE', 'mult_expr'), [
Tree(Token('RULE', 'unary_expr'), [
Tree(Token('RULE', 'unary_operator'), [
Tree(Token('RULE', 'unary_operator_minus'), [])]), 
Tree(Token('RULE', 'primary_expr'), [
Tree(Token('RULE', 'literal'), [
Tree(Token('RULE', 'integer_literal'), [
Tree(Token('RULE', 'decimal_literal'), [Token('__ANON_0', '1'), Token('DIGIT', '0')])])])])])])])])])])])])]), 
Tree(Token('RULE', 'annotation_appl_param'), [Token('IDENTIFIER', 'max'), 
Tree(Token('RULE', 'const_expr'), [
Tree(Token('RULE', 'or_expr'), [
Tree(Token('RULE', 'xor_expr'), [
Tree(Token('RULE', 'and_expr'), [
Tree(Token('RULE', 'shift_expr'), [
Tree(Token('RULE', 'add_expr'), [
Tree(Token('RULE', 'mult_expr'), [
Tree(Token('RULE', 'unary_expr'), [
Tree(Token('RULE', 'primary_expr'), [
Tree(Token('RULE', 'literal'), [
Tree(Token('RULE', 'integer_literal'), [
Tree(Token('RULE', 'decimal_literal'), [Token('__ANON_0', '1'), Token('DIGIT', '0')])])])])])])])])])])])])])])]), 
Tree(Token('RULE', 'type_spec'), [
Tree(Token('RULE', 'simple_type_spec'), [
Tree(Token('RULE', 'base_type_spec'), [
Tree(Token('RULE', 'integer_type'), [
Tree(Token('RULE', 'signed_int'), [
Tree(Token('RULE', 'signed_long_int'), [])])])])])]), 
Tree(Token('RULE', 'declarators'), [
Tree(Token('RULE', 'declarator'), [
Tree(Token('RULE', 'simple_declarator'), [Token('IDENTIFIER', 'long_value')])])])])
```
</details>

Difference seems to be a `None` at the end of the list of things givin to annotation_appl in 1.1.1, but not in 0.8.1

```
Tree(annotation_appl, [Tree(scoped_name, [Token(IDENTIFIER, 'key')])]), 
```

```
Tree(Token('RULE', 'annotation_appl'), [Tree(Token('RULE', 'scoped_name'), [Token('IDENTIFIER', 'key')]), None])
```
