### ISSUE TITLE
/libexample_interfaces__rosidl_generator_c.so: undefined symbol: rosidl_runtime_c__double__Sequence__are_equal

### ISSUE THREAD

**Issue by wpd** [ros2/rosidl#682]
## Bug report

Following up on a question I posted on [answers.ros.org](https://answers.ros.org/question/400197/did-ros-galactic-example-interfaces-break/), I can no longer use a `Dockerfile` as simple as:

```
FROM ros:galactic

WORKDIR /opt/ros/overlay_ws/src
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    git clone https://github.com/ros2/examples.git -b $ROS_DISTRO && \
    apt update && \
    cd .. && \
    rosdep install -y --from-paths src && \
    colcon build --packages-select examples_rclcpp_minimal_action_server --mixin "release"


WORKDIR /opt/ros/overlay_ws
```

**Required Info:**

- Operating System:
  - Shouldn't matter, but I'm running Docker on a Ubuntu 20.04 machine
- Installation type:
  - Installed from `ros:galactic` container
- Version or commit hash:
  - Image ID: `cf0dc73b6e54`
- DDS implementation:
  - default (CycloneDDS)
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
- Create a `Dockerfile` with the contents shown above.
- Build it with:
```
$ docker build -t my/ros:app .
```
- Launch the container with:
```
$ docker run -it --rm my/ros:app
```
- Execute `ros2 action send_goal` within the container:
```
# ros2 action send_goal /fibonacci example_interfaces/action/Fibonacci "{}"
```
#### Expected behavior
At this point, I'm not sure anymore :-)... this has been stripped down considerably from an existing setup.  I guess I would expect the command to time out or complain that nobody was listening for the goal that I sent.

#### Actual behavior
```
# ros2 action send_goal /fibonacci example_interfaces/action/Fibonacci "{}"
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 46, in import_type_support
    return importlib.import_module(module_name, package=pkg_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /opt/ros/galactic/lib/libexample_interfaces__rosidl_generator_c.so: undefined symbol: rosidl_runtime_c__double__Sequence__are_equal
...
```

**Comment by wpd** [comment]
Yep... I just noticed I was missing that.
Confirm... I was _sure_ I had it in there.  But after I submitted my bug report, I noticed that the gremlins snuck in and removed it from my `Dockerfile`.  Sorry for the noise.
